export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";

export const CREATE_BOARD = "CREATE_BOARD";
export const RETRIEVE_BOARDS = "RETRIEVE_BOARDS";
export const RETRIEVE_BOARD = "RETRIEVE_BOARD";
export const UPDATE_BOARD = "UPDATE_BOARD";
export const DELETE_BOARD = "DELETE_BOARD";
export const DELETE_ALL_BOARDS = "DELETE_ALL_BOARDS";
