export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";

export const CREATE_BOARD = "CREATE_BOARD";
export const RETRIEVE_BOARDS = "RETRIEVE_BOARDS";
export const RETRIEVE_BOARD = "RETRIEVE_BOARD";
export const UPDATE_BOARD = "UPDATE_BOARD";
export const DELETE_BOARD = "DELETE_BOARD";
export const DELETE_ALL_BOARDS = "DELETE_ALL_BOARDS";

export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const RETRIEVE_USER = "RETRIEVE_USER";
export const COMPARE_CURRENT_PASSWORD = "COMPARE_CURRENT_PASSWORD";
export const RETRIEVE_BY_ACCOUNT = "RETRIEVE_BY_ACCOUNT";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE_LOGGED_USER = "UPDATE_LOGGED_USER";
